services:
  - type: web
    name: sangmata-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_ID
        value: 25136703
      - key: API_HASH
        value: "accfaf5ecd981c67e481328515c39f89"
      - key: BOT_TOKEN
        value: "8244179451:AAFW8SLabiTyCuTge2fz5LL6VA5sNOH_3pQ"
